cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('<int:item_id>/', views.Add_to_cart , name="Add_to_cart"  ),   
    path('add/<int:item_id>/', views.add_one_cart , name="add_one_cart"  ),
    path('remove/<int:item_id>/', views.remove_one_cart , name="remove_one_cart"  ),
    path('delete/<int:item_id>/', views.delect_from_cart , name="delect_from_cart"  ),
    path('cart_to_wishlist/<int:item_id>/', views.cart_to_wishlist , name="cart_to_wishlist"  ),
    path('wish_to_cart/<int:item_id>/', views.wish_to_cart , name="wish_to_cart" ),
    path('delete_wish/<int:item_id>/', views.delect_from_wishlist , name="delect_from_wishlist"  ),
    path('add_wish/<int:item_id>/', views.add_to_wishlist, name="add_to_wishlist"  ),
    path('', views.cart , name="cart"  ),
    path('wishlist/', views.wishlist , name="wishlist"),
]

                                         

e_dukan/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("core.urls")),
    path("customer/", include("customer.urls")),
    path("products/", include("products.urls")),
    path("cart/", include("cart.urls")),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name='products'

urlpatterns = [
    path('<int:item_id>/', views.detail , name="item_detail" ),
    path('<int:id>/reviews', views.all_reviews , name="all_reviews" ),
    path('shop/', views.shop, name="shop" ),
    path("category/<int:itemCategory>/",views.category, name="item_category"),
    path("group/<int:category_sub>/",views.Group_category, name="Group_category"),
    
]

cart/models.py
from products.models import *
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Cart(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    customer=models.ForeignKey(User, on_delete=models.CASCADE)
    qty=models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.customer.first_name
    
    def get_total(self):
        return self.qty* self.product.price


class Wishlist(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    customer=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.customer.first_name
    

cart/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from products.models import *
from .models import *
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def Add_to_cart(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        if Cart.objects.filter(customer_id=user,product=item):
            qty=Cart.objects.get(customer_id=user,product=item)
            qty.qty+=1
            qty.save()
        else:
            add=Cart(customer_id=user,product=item,qty=1)
            add.save()
        return redirect(f"/products/{item_id}")
    else:
        return redirect("/customer/login")

def wish_to_cart(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        if Cart.objects.filter(customer_id=user,product=item):
            qty=Cart.objects.get(customer_id=user,product=item)
            qty.qty+=1
            qty.save()
        else:
            add=Cart(customer_id=user,product=item,qty=1)
            add.save()
        return redirect("/cart/wishlist")
    else:
        return redirect("/customer/login")


def cart_to_wishlist(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        if Wishlist.objects.filter(customer_id=user,product=item):
            qty=Cart.objects.get(customer_id=user,product=item)
            qty.delete()
        else:
            add=Wishlist(customer_id=user,product=item)
            add.save()
            qty=Cart.objects.get(customer_id=user,product=item)
            qty.delete()
        return redirect("/cart")
    else:
        return redirect("/customer/login")


def add_to_wishlist(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        if Wishlist.objects.filter(customer_id=user,product=item):
            pass
        else:
            add=Wishlist(customer_id=user,product=item)
            add.save()
        return redirect(f"/products/{item_id}")
    else:
        return redirect("/customer/login")


def delect_from_wishlist(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        item=Wishlist.objects.get(customer_id=user,product=item)
        item.delete()
        return redirect("/cart/wishlist")
    else:
        return redirect("/customer/login")

def wishlist(request):
    if  request.user.is_authenticated:
        context={
        'wishlist_item':len(Wishlist.objects.filter(customer_id=request.user.id)),
        'cart_item':len(Cart.objects.filter(customer_id=request.user.id)),
        'wishlist_items':Wishlist.objects.filter(customer_id=request.user.id)
        }
        return render(request, "wishlist.html",context)
    else:
        return redirect("/customer/login")

def add_one_cart(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        qty=Cart.objects.get(customer_id=user,product=item)
        qty.qty+=1
        qty.save()
        return redirect("/cart")
    else:
        return redirect("/customer/login")


def remove_one_cart(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        if Cart.objects.filter(customer_id=user,product=item)[0].qty==1:
            qty=Cart.objects.get(customer_id=user,product=item)
            qty.delete()
        else:    
            qty=Cart.objects.get(customer_id=user,product=item)
            qty.qty-=1
            qty.save()
        return redirect('/cart')
    else:
        return redirect("/customer/login")

def delect_from_cart(request,item_id):
    if  request.user.is_authenticated:
        item=Product.objects.get(id=item_id)
        user=request.user.id
        qty=Cart.objects.get(customer_id=user,product=item)
        qty.delete()    
        return redirect('/cart')
    else:
        return redirect("/customer/login")


def cart(request):
    if  request.user.is_authenticated:
        user=request.user.id
        items=Cart.objects.filter(customer_id=user)
        subtotal=float()
        for i in range(len(items)):
            subtotal+=items[i].product.price*items[i].qty
        context={
        'cart_item':len(Cart.objects.filter(customer_id=request.user.id)),
        'wishlist_item':len(Wishlist.objects.filter(customer_id=request.user.id)),
        'cart_items':Cart.objects.filter(customer_id=request.user.id),
        'subtotal':subtotal,
        'total':subtotal+100
        }
        return render(request, "cart.html",context)
    else:
        return redirect("/customer/login")

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Cart{% endblock%}
{% block body%} 

    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 150px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">Shopping Cart</h1>
            
        </div>
    </div>
    <!-- Page Header End -->
{% if cart_items%}
    <!-- Cart Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Remove</th>
                            <th>Add to wishlist</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        
                     
                        
                        {% for item in cart_items%}
                        <tr>
                            <td class="align-middle"><img src="/media/Item_image/{{item.product.image}}" alt="" style="width: 50px;">
                                <a href="{% url "products:item_detail" item.product.id %}">{{item.product.product_name}}</a></td>
                            <td  class="align-middle">{{item.product.price}}</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn"><a href={% url "cart:remove_one_cart" item.product.id %}>
                                        <button class="btn btn-sm btn-primary btn-minus" >
                                        <i class="fa fa-minus"></i>
                                        </button> </a>
                                    </div>
                                    <p  class="form-control form-control-sm bg-secondary text-center">{{item.qty}}</p>
                                    <div class="input-group-btn"> <a href={% url "cart:add_one_cart" item.product.id %}>
                                        <button class="btn btn-sm btn-primary btn-plus">
                                             <i class="fa fa-plus"></i>
                                        </button></a>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">{{item.get_total}}</td>
                            <td class="align-middle">
                                <a href={% url "cart:delect_from_cart" item.product.id %}>
                                <button class="btn btn-sm btn-primary"><i class="fa fa-times"></i></button>
                                
                                </a>
                            </td>
                            <td class="align-middle">
                                <a href={% url "cart:cart_to_wishlist" item.product.id %}>
                                save for later
                                </a>
                            </td>
                        </tr>
                        {% endfor%}
                        

                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Subtotal</h6>
                            
                            <h6 class="font-weight-medium">Rs. {{subtotal}}</h6>
                            
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            {% if subtotal %}
                            <h6 class="font-weight-medium">Rs. 100</h6>
                            {% endif%}
                        </div>
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Total</h5>
                            <h5 class="font-weight-bold">Rs. {{total}}</h5>
                        </div>
                       <a href="/checkout"> <button class="btn btn-block btn-primary my-3 py-3">Proceed To Checkout</button>
                       </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->
{% else%}
<h2> Empty Cart</h2>
{% endif%}
    {% endblock%}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title%}E-DUKAN{% endblock%}

                {% block body%} 
    <!-- Featured Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                    <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center border mb-4" style="padding: 30px;">
                    <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Featured End -->


    <!-- Categories Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right">   </p>
                    <a href={% url "products:Group_category" 1  %} class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" width="300" src="{% static 'img/mobile_3.jpg'%}" alt="">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Mobiles & Tablets</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right">   </p>
                    <a href={% url "products:Group_category" 2  %} class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" width="300" src="{% static 'img/laptop.jpg'%}" alt="">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Computers & laptops</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right">   </p>
                    <a href={% url "products:Group_category" 3  %} class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" height="300" src="{% static 'img/camera.jpg'%}" alt="">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Cameras</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right">  </p>
                    <a href={% url "products:Group_category" 4  %} class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" width="300" src="{% static 'img/tv.jpg'%}" alt="">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Television</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right">   </p>
                    <a href={% url "products:Group_category" 5  %} class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" width="300" src="{% static 'img/printer.jpg'%}" alt="">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Computer Peripherals</h5>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 pb-1">
                <div class="cat-item d-flex flex-column border mb-4" style="padding: 30px;">
                    <p class="text-right">    </p>
                    <a href={% url "products:Group_category" 6  %} class="cat-img position-relative overflow-hidden mb-3">
                        <img class="img-fluid" width="300" src="{% static 'img/headphone.jpg'%}" alt="">
                    </a>
                    <h5 class="font-weight-semi-bold m-0">Audio</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Categories End -->



    <!-- Products Start -->
    <div class="container-fluid py-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Just Arrived</span></h2>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel related-carousel">

                    {% for item in latest %}
                    <div class="card product-item border-0" style="height:20;">
                        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0" >
                            <a href="{% url "products:item_detail" item.id %}">
                            <img class="img-fluid w-100" style="max-width: 350px;" src="/media/{{item.image}}" alt="">
                        </a>
                        </div>
                        <div class="card-body border-left border-right p-0 pt-4 pb-3">
                            <a href="{% url "products:item_detail" item.id %}">
                            <h5>{{item.product_name}}</h5></a>
                            <a href={% url "products:all_reviews" item.id%}>
                            <small style="color:#808000;"> Rating: {{item.rating_count}}/5 | ({{item.review_count}})reviews </small>
                            </a>
                            <div class="d-flex ">
                         
                                <h5 style='color:red;'>₹.{{item.price}}<small> <small style='color:black;' >  <del>₹.{{item.actual_price}}<del></small></small></h5>
                            
                                </div>
                        </div> 
                    </div>
                    {% endfor%}
                    
                </div>
            </div>
        </div>
    </div>
    <!-- Products End -->


    <!-- Vendor Start -->
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel vendor-carousel">
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-1.jpg'%}" alt="">
                    </div>
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-2.jpg'%}" alt="">
                    </div>
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-3.jpg'%}" alt="">
                    </div>
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-4.jpg'%}" alt="">
                    </div>
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-5.jpg'%}" alt="">
                    </div>
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-6.jpg'%}" alt="">
                    </div>
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-7.jpg'%}" alt="">
                    </div>
                    <div class="vendor-item border p-4">
                        <img src="{% static 'img/vendor-8.jpg'%}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Vendor End -->

    {% endblock%}
   

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title%}Login{% endblock%}
{% block body%} 
    <!-- Page Header Start -->
    <div class="container-fluid bg-secondary mb-5">
        <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 100px">
            <h1 class="font-weight-semi-bold text-uppercase mb-3">LogIN</h1>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Checkout Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <div class="mb-4">
                    <h4 class="font-weight-semi-bold mb-4">Log in</h4>
                    {% if messages %}
                    <ul class="messages">
                    {% for message in messages %}
                    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                    {% endfor %}
                </ul>
                {% endif %}
                    <form method="post" action="">
                    {% csrf_token %}
                        <div class="row">  
                        <div class="col-md-6 form-group">
                            <label>Email</label>
                            <input class="form-control" name="email" type="email">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Password</label>
                            <input class="form-control" type="password" name="password">
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" class="btn btn-primary">Login</button>
                            <a href="/customer/register"> New user</a>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

    {% endblock%}

templates/review.html
{% extends 'base.html' %}
{% load static %}
{% block title%}{% endblock%}
{% block body%} 
    <!-- Page Header Start -->
    
    <!-- Page Header End -->


    <!-- Shop Detail Start -->
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 pb-5">     
                <h3 style="font-weight: bold;">Customer reviews</h3><hr>
                        <p style="font-weight:bold; color:black;"> Product rating {{rat_list.5}} out of 5</p>
                        <p> {{review.count}} golbal ratings </p>
                        
                        <table class="table ">
                            <tbody>
                                <tr>
                                    <th scope="col">1 star</th>

                                    <th scope="col">
                            <div class="progress col-lg">  
                                <div class="progress-bar bg-info" role="progressbar" style="width: {{rat_list.0}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                              </div></th>
                              <th scope="col">{{rat_list.0}}%</th>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                
                                <th scope="col">2 star</th>
                                <th scope="col">
                              <div class="progress">
                                <div class="progress-bar bg-info" role="progressbar" style="width: {{rat_list.1}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                              </div></th>
                              <th scope="col">{{rat_list.1}}%</th>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                <th scope="col">3 star</th>
                            <th scope="col">
                              <div class="progress">
                                <div class="progress-bar bg-info" role="progressbar" style="width: {{rat_list.2}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                              </div></th>
                              <th scope="col">{{rat_list.2}}%</th>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                <th scope="col">4 star</th>
                                
                                <th scope="col">
                              <div class="progress" >
                                <div class="progress-bar bg-info" role="progressbar" style="width: {{rat_list.3}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                              </div></th>
                              <th scope="col">{{rat_list.3}}%</th>
                            </tr>
                        </tbody>
                        <tbody>
                            <tr>
                                <th scope="col">5 star</th>
                                
                                <th scope="col">
                              <div class="progress">
                                <div class="progress-bar bg-info" role="progressbar" style="width: {{rat_list.4}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><div>
                              </div></th>
                              <th scope="col">{{rat_list.4}}%</th>
                            </tr>
                        </tbody>
                    </table>

                              <br>
                              <a href="{% url "products:item_detail" product.id %}">Write a review</a>
                              
                            </div>
            

            <div class="col-lg-7 pb-5">
                <h1 class="font-weight-semi-bold">{{product.product_name}}</h1>
                <a href="{% url "products:item_detail" product.id %}">visit the {{product.brand}} store</a>
                <a href={% url "products:all_reviews" product.id%}>
                    <p style="color:#808000;"> Rating: {{product.rating_count}}/5 | ({{product.review_count}})reviews </p>
                    </a>
                <hr>
                <a href={% url "products:all_reviews" product.id%}>
                    <h6 style="color:#808000;"><small> M.R.P.: <del>₹.{{product.actual_price}}</del></small> </h6>
                    </a>        
                  <h4 class="mb-4" style="color:#DC143C;"> ₹.{{product.price}}</h4>
                 <h5> About this item </h5>
                 <hr>
                <p class="mb-4">{{product.desc}}</p>
                {% if ram_list%}
                <div class="d-flex mb-3">
                    <p class="text-dark font-weight-medium mb-0 mr-3">RAM:</p>
                    <form>
{% for ram in ram_list%}
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" name="size">
                            <label class="custom-control-label" >{{ram.ram}} GB</label>
                        </div>
{% endfor%}
                    </form>
                </div>
                {% endif%}
                {% if color%}

                <div class="d-flex mb-4">
                    <p class="text-dark font-weight-medium mb-0 mr-3">Colors:</p>
                    <form>
                        {% for color in color%}
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" class="custom-control-input" id="color-1" name="color">
                            <label class="custom-control-label" for="color-1">{{color.ram}}</label>
                        </div>
{% endfor%}
                       
                    </form>
                </div>
                {% endif%}
                <div class="d-flex align-items-center mb-4 pt-2">
                    <a href={% url "cart:Add_to_cart" product.id %}> 
                    <button class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></i> Add To Cart</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
               
                        <div class="row">
                            <div class="col-md-10">
                                <h4 class="mb-4"> reviews for "{{product.product_name}}"</h4>
                        {% for i in review%}
                               {% if i.name%}
                                <h5><small>{{i.name}}</small></h5>  
{% else %}
<h5><small>E-dukan Customer </small></h5>
{% endif%}
                                        <div class="text-primary mb-2">
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star-half-alt"></i>
                                            <i class="far fa-star"></i>
                                            <small ><i style="font-weight:bold; color:black;">{{i.comment}}</i></small>
                                            </div>
                                            
                                            <h6><small> Reviewed on {{i.date}}</small></h6>
                                            <p>{{i.review}}</p>
                                            <h6><small>{{i.helpfull}} people found this helpful</small></h6>
                                            <a href="/products/1/reviews/?helpfull={{i.id}}">
                                            <button type="button" class="btn btn-outline-dark btn-sm">Helpful</button></a>
                                            <hr>

                                  
                                
                            {% endfor%}
                           
                            </div>    
                            
                            
            </div>
        </div>
    </div>
    <!-- Shop Detail End -->


{% endblock%}